# Generated by Django 5.1.2 on 2024-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='product_page.hashtag'),
        ),
        migrations.DeleteModel(
            name='ProductHashtag',
        ),
    ]
