# Generated by Django 5.1.1 on 2024-10-25 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0003_store_alter_product_image_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_page.store'),
            preserve_default=False,
        ),
    ]
