# Generated by Django 5.1.1 on 2024-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0004_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/img'),
        ),
    ]
