# Generated by Django 5.1.1 on 2024-10-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0006_alter_productentry_price'),
        ('product_page', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard_admin.productentry'),
        ),
    ]
