# Generated by Django 5.1.2 on 2024-10-25 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('dashboard_admin', '0004_productentry_p_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='last_modified',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='location',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_admin.tokoentry'),
            preserve_default=False,
        ),
    ]
