# Generated by Django 5.1.2 on 2024-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_last_modified_journalentry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='store',
            field=models.CharField(max_length=255),
        ),
    ]
