# Generated by Django 5.1.2 on 2024-10-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_price', models.IntegerField()),
                ('p_description', models.TextField()),
                ('p_toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard_admin.tokoentry')),
            ],
        ),
    ]
