# Generated by Django 5.1.2 on 2024-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0002_alter_productentry_id_alter_tokoentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokoentry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
