# Generated by Django 5.1.2 on 2024-10-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0003_alter_tokoentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
