# Generated by Django 5.1.2 on 2024-10-25 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0005_rename_p_description_productentry_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
