# Generated by Django 5.1.1 on 2024-10-25 15:24

import dashboard_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0006_alter_productentry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard_admin.models.get_image_filename),
        ),
    ]
